/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ClearanceRouteImport } from './routes/clearance'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TopPicksRouteImport } from './routes/top-picks'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAdministratorsRouteImport } from './routes/admin.administrators'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsCategoryRouteImport } from './routes/cars.$category'
import { Route as CategorySplatRouteImport } from './routes/category.$'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearanceRoute = ClearanceRouteImport.update({
  id: '/clearance',
  path: '/clearance',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TopPicksRoute = TopPicksRouteImport.update({
  id: '/top-picks',
  path: '/top-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorsRoute = AdminAdministratorsRouteImport.update({
  id: '/administrators',
  path: '/administrators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCategoryRoute = CarsCategoryRouteImport.update({
  id: '/cars/$category',
  path: '/cars/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySplatRoute = CategorySplatRouteImport.update({
  id: '/category/$',
  path: '/category/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/best-sellers': typeof BestSellersRoute
  '/cart': typeof CartRoute
  '/clearance': typeof ClearanceRoute
  '/deals': typeof DealsRoute
  '/delivery': typeof DeliveryRoute
  '/favorites': typeof FavoritesRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/search': typeof SearchRoute
  '/top-picks': typeof TopPicksRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cars/$category': typeof CarsCategoryRoute
  '/category/$': typeof CategorySplatRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-sellers': typeof BestSellersRoute
  '/cart': typeof CartRoute
  '/clearance': typeof ClearanceRoute
  '/deals': typeof DealsRoute
  '/delivery': typeof DeliveryRoute
  '/favorites': typeof FavoritesRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/search': typeof SearchRoute
  '/top-picks': typeof TopPicksRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cars/$category': typeof CarsCategoryRoute
  '/category/$': typeof CategorySplatRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/cars': typeof CarsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/best-sellers': typeof BestSellersRoute
  '/cart': typeof CartRoute
  '/clearance': typeof ClearanceRoute
  '/deals': typeof DealsRoute
  '/delivery': typeof DeliveryRoute
  '/favorites': typeof FavoritesRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/search': typeof SearchRoute
  '/top-picks': typeof TopPicksRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cars/$category': typeof CarsCategoryRoute
  '/category/$': typeof CategorySplatRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/best-sellers'
    | '/cart'
    | '/clearance'
    | '/deals'
    | '/delivery'
    | '/favorites'
    | '/new-arrivals'
    | '/search'
    | '/top-picks'
    | '/admin/activity'
    | '/admin/administrators'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/products'
    | '/admin/settings'
    | '/cars/$category'
    | '/category/$'
    | '/product/$id'
    | '/admin/'
    | '/cars/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-sellers'
    | '/cart'
    | '/clearance'
    | '/deals'
    | '/delivery'
    | '/favorites'
    | '/new-arrivals'
    | '/search'
    | '/top-picks'
    | '/admin/activity'
    | '/admin/administrators'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/products'
    | '/admin/settings'
    | '/cars/$category'
    | '/category/$'
    | '/product/$id'
    | '/admin'
    | '/cars'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/best-sellers'
    | '/cart'
    | '/clearance'
    | '/deals'
    | '/delivery'
    | '/favorites'
    | '/new-arrivals'
    | '/search'
    | '/top-picks'
    | '/admin/activity'
    | '/admin/administrators'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/products'
    | '/admin/settings'
    | '/cars/$category'
    | '/category/$'
    | '/product/$id'
    | '/admin/'
    | '/cars/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BestSellersRoute: typeof BestSellersRoute
  CartRoute: typeof CartRoute
  ClearanceRoute: typeof ClearanceRoute
  DealsRoute: typeof DealsRoute
  DeliveryRoute: typeof DeliveryRoute
  FavoritesRoute: typeof FavoritesRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  SearchRoute: typeof SearchRoute
  TopPicksRoute: typeof TopPicksRoute
  CarsCategoryRoute: typeof CarsCategoryRoute
  CategorySplatRoute: typeof CategorySplatRoute
  ProductIdRoute: typeof ProductIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clearance': {
      id: '/clearance'
      path: '/clearance'
      fullPath: '/clearance'
      preLoaderRoute: typeof ClearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-picks': {
      id: '/top-picks'
      path: '/top-picks'
      fullPath: '/top-picks'
      preLoaderRoute: typeof TopPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administrators': {
      id: '/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AdminAdministratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$category': {
      id: '/cars/$category'
      path: '/cars/$category'
      fullPath: '/cars/$category'
      preLoaderRoute: typeof CarsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$': {
      id: '/category/$'
      path: '/category/$'
      fullPath: '/category/$'
      preLoaderRoute: typeof CategorySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAdministratorsRoute: typeof AdminAdministratorsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAdministratorsRoute: AdminAdministratorsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BestSellersRoute: BestSellersRoute,
  CartRoute: CartRoute,
  ClearanceRoute: ClearanceRoute,
  DealsRoute: DealsRoute,
  DeliveryRoute: DeliveryRoute,
  FavoritesRoute: FavoritesRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  SearchRoute: SearchRoute,
  TopPicksRoute: TopPicksRoute,
  CarsCategoryRoute: CarsCategoryRoute,
  CategorySplatRoute: CategorySplatRoute,
  ProductIdRoute: ProductIdRoute,
  CarsIndexRoute: CarsIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
