/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockSupabaseClient() {
  const createQueryBuilder = (initialData: any = null): any => {
    let lastPayload: any = initialData;
    const resultPromise = Promise.resolve({ data: [], error: null, count: 0 });

    const builder: any = new Proxy(
      {},
      {
        get(_target, prop) {
          if (typeof prop === "symbol") {
            return undefined;
          }
          if (prop === "then") {
            return (onfulfilled?: (val: any) => any, onrejected?: (reason: any) => any) =>
              resultPromise.then(onfulfilled, onrejected);
          }
          if (prop === "catch") {
            return (onrejected?: (reason: any) => any) => resultPromise.catch(onrejected);
          }
          if (prop === "finally") {
            return (onfinally?: () => void) => resultPromise.finally(onfinally);
          }
          if (prop === "single" || prop === "maybeSingle") {
            return async () => ({ data: lastPayload ?? null, error: null });
          }
          return (...args: any[]) => {
            if (["insert", "upsert", "update"].includes(String(prop)) && args[0]) {
              lastPayload = Array.isArray(args[0]) ? args[0][0] : args[0];
            }
            return builder;
          };
        },
      },
    );
    return builder;
  };

  return {
    from: () => createQueryBuilder(),
    auth: {
      getUser: async () => ({ data: { user: null }, error: null }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getClaims: async () => ({ data: { claims: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: new Error("Supabase is not configured yet."),
      }),
      signOut: async () => ({ error: null }),
    },
    storage: {
      from: () => ({
        download: async () => ({ data: null, error: new Error("Supabase storage not configured") }),
        upload: async () => ({ data: null, error: new Error("Supabase storage not configured") }),
        getPublicUrl: () => ({ data: { publicUrl: "" } }),
      }),
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
}

const DEFAULT_SUPABASE_URL = "https://olhxisnuqdqelkaxvroi.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ADWuB_lQsQchIV8oOsRHVw_8nz4Cl7k";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    import.meta.env["VITE_SUPABASE_URL"] ||
    (typeof process !== "undefined"
      ? process.env?.["VITE_SUPABASE_URL"] || process.env?.["SUPABASE_URL"]
      : undefined) ||
    DEFAULT_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    (typeof process !== "undefined"
      ? process.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env?.["SUPABASE_PUBLISHABLE_KEY"]
      : undefined) ||
    DEFAULT_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn("[Supabase] Missing Supabase environment variable(s). Mock client active.");
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
